baseURL = 'https://github.io/strongwinderic/Sea2Sky'
languageCode = 'en-us'
title = 'Sea2Sky'
theme = 'ananke'
menu = ['about', 'blog']
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true